export const configStepScale = {
  maxWidth: 890,
  spacing: 29,
  logoSize: 95,
  titleSize: 38,
  separatorHeight: 2,
  controlHeight: 67,
  controlRadius: 5,
  controlTextSize: 19,
  arrowSize: 29,
  listTopSpacing: 29,
  listHeight: 317,
  rowHeight: 63,
  rowDivider: 2,
  avatarSize: 40,
  avatarRadius: 5,
  guildNameSize: 16,
  guildNameGap: 19,
  starSize: 25,
  nextButtonHeight: 67,
  nextButtonTextSize: 23,
  sidePadding: 38,
};
