export const configStepTwoScale = {
  maxWidth: 960,
  containerGap: 29,
  logoSize: 95,
  titleSize: 38,
  separatorHeight: 2,
  firstLabelTopSpacing: 29,
  fieldGap: 29,
  labelSize: 18,
  controlHeight: 67,
  controlRadius: 5,
  controlTextSize: 19,
  controlSidePadding: 38,
  arrowSize: 29,
  maxVisibleOptions: 5,
  optionHeight: 63,
  optionTextSize: 16,
  nextButtonHeight: 67,
  nextButtonTextSize: 23,
};
